name: CD

on:
  # Dispara manualmente
  workflow_dispatch:
  # Dispara após o CI (Build/Testes) ser concluído
  workflow_run:
    workflows: ["CI"]
    branches: [ "main" ]
    types: [completed]

env:
  # Recursos do Azure
  RESOURCE_GROUP: rg-fcg-payments
  CONTAINER_APP_NAME: fnc-fcg-payments
  APP_SOURCE_PATH: ./FCGPagamentos.Worker
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC - UAMI)
        id: login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Deploy Source Code Natively (Azure Build)
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          appSourcePath: ${{ env.APP_SOURCE_PATH }}
          
