name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: "8.0.x" }
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet publish ./src/FCGPagamentos.Worker/FCGPagamentos.Worker.csproj -c Release -o ./out/func
      - uses: actions/upload-artifact@v4
        with: { name: func-publish, path: ./out/func }
